# -*-python-*-

from SCons.Errors import EnvironmentError

try:
    Import("env")
    pyenv = env.Clone(tools = ['pybind11'])

    pyenv.AppendUnique(LIBS  = ['statiskit_stl'])

    exclude = """
    """.split()

    sources = [source for source in pyenv.Glob('*.*') if source.name not in exclude]

    targets = pyenv.PyBind11Extension("../statiskit/stl/__stl", sources)
    Alias("py", targets)
    Alias("install", targets)
    pyenv.Depends(targets, "cpp")

    targets = pyenv.PythonPackage(statiskit='../statiskit')
    Alias("py", targets)
    Alias("install", targets)
    pyenv.Depends(targets, "cpp")
except EnvironmentError:
    Alias("py", [])
    Alias("install", [])
    pass
except Exception:
    raise