#include "_stl.h"

bool  (::statiskit::stl::Generator< ::std::set< ::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >, ::std::less< ::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > > >, ::std::allocator< ::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > > > > >::*method_pointer_30be644c9a6f5492bf552e9847dd709b)()const= &::statiskit::stl::Generator< class ::std::set< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >, struct ::std::less< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > >, class ::std::allocator< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > >::is_valid;
class ::statiskit::stl::Generator< class ::std::set< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >, struct ::std::less< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > >, class ::std::allocator< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > > & (::statiskit::stl::Generator< ::std::set< ::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >, ::std::less< ::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > > >, ::std::allocator< ::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > > > > >::*method_pointer_a7cb81625e2f579199aeaaecca69d69f)()= &::statiskit::stl::Generator< class ::std::set< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >, struct ::std::less< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > >, class ::std::allocator< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > >::operator++;
class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >  (::statiskit::stl::Generator< ::std::set< ::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > >, ::std::less< ::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > > >, ::std::allocator< ::std::basic_string< char, ::std::char_traits< char >, ::std::allocator< char > > > > >::*method_pointer_10ecdbe4ae2053789496273580871f32)()const= &::statiskit::stl::Generator< class ::std::set< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >, struct ::std::less< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > >, class ::std::allocator< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > >::value;

namespace autowig {
    void method_decorator_a7cb81625e2f579199aeaaecca69d69f(class ::statiskit::stl::Generator< class ::std::set< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >, struct ::std::less< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > >, class ::std::allocator< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > > & instance, const class ::statiskit::stl::Generator< class ::std::set< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >, struct ::std::less< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > >, class ::std::allocator< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > > & param_out) { instance.operator++() = param_out; }
}

void wrapper_745e4933f5b250d9bc5232fe864d0cf7(pybind11::module& module)
{

    pybind11::class_<class ::statiskit::stl::Generator< class ::std::set< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >, struct ::std::less< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > >, class ::std::allocator< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > >, autowig::HolderType< class ::statiskit::stl::Generator< class ::std::set< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >, struct ::std::less< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > >, class ::std::allocator< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > > >::Type > class_745e4933f5b250d9bc5232fe864d0cf7(module, "_Generator_745e4933f5b250d9bc5232fe864d0cf7", "");
    class_745e4933f5b250d9bc5232fe864d0cf7.def(pybind11::init< class ::std::set< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >, struct ::std::less< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > >, class ::std::allocator< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > const & >());
    class_745e4933f5b250d9bc5232fe864d0cf7.def(pybind11::init< class ::statiskit::stl::Generator< class ::std::set< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > >, struct ::std::less< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > >, class ::std::allocator< class ::std::basic_string< char, struct ::std::char_traits< char >, class ::std::allocator< char > > > > > const & >());
    class_745e4933f5b250d9bc5232fe864d0cf7.def("is_valid", method_pointer_30be644c9a6f5492bf552e9847dd709b, "");
    class_745e4933f5b250d9bc5232fe864d0cf7.def("__next__", method_pointer_a7cb81625e2f579199aeaaecca69d69f, pybind11::return_value_policy::reference_internal, "");
    class_745e4933f5b250d9bc5232fe864d0cf7.def("__next__", autowig::method_decorator_a7cb81625e2f579199aeaaecca69d69f);
    class_745e4933f5b250d9bc5232fe864d0cf7.def("value", method_pointer_10ecdbe4ae2053789496273580871f32, "");

}