# -*-python-*-

import os
import platform

system = platform.system().lower()

Import("env")

cppenv = env.Clone(tools = ['cpp'])

cppenv.AppendUnique(CPPDEFINES = ['LIBSTATISKIT_STL'])

exclude = """
""".split()

sources = [source for source in cppenv.Glob('*.*') if not source.name in exclude]

targets = cppenv.CppLibrary("statiskit_stl", sources)
Alias("cpp", targets)
Alias("install", targets)