# -*-python-*-

import os
import platform

system = platform.system().lower()

Import("env")

cppenv = env.Clone(tools = ['cpp'])

cppenv.AppendUnique(CPPDEFINES = ['LIBSTATISKIT_STL'])

exclude = """
""".split()

sources = [source for source in cppenv.Glob('*.*') if not source.name in exclude]

targets = cppenv.CppLibrary("statiskit_stl", sources)
Alias("cpp", targets)
Alias("autowig", targets)
Alias("install", targets)

try:
    wigenv = cppenv.Clone(tools = ['wig'])

    targets = wigenv.BoostPythonWIG('statiskit_stl', [target for target in targets if target.name.endswith('.h')],
                                    module='../py/_stl.cpp',
                                    decorator='../py/statiskit/stl/_stl.py',
                                    parser_bootstrap=1,
                                    controller='AutoWIG.py',
                                    generator='AutoWIG.py')
    Alias("autowig", targets)
    Alias("install", targets)
except EnvironmentError:
    pass
except Exception:
    raise