package:
  name: python-statiskit_stl
  version: {{ GIT_DESCRIBE_VERSION }}

source:
  path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

about:
  home: http://statiskit-stl.readthedocs.org
  license: Apache License 2.0
  summary: Minimal Interpreted Interfaces for Containers of the STL C++ Template Library

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libtoolchain
    - python-toolchain
  host:
    - libpybind11-dev
    - libstatiskit_stl
    - python
  run:
    - {{ pin_compatible('libstatiskit_stl', exact=True) }}
    - python

test:                                               
  requires:
    - python-toolchain
  imports:
    - statiskit.stl
  source_files:                                
    - test/test_*.py
  commands:                                       
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and linux" [linux]
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and osx"   [osx]
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and win"   [win]
